version: '2'
services:
    database:
        image: postgres:latest
        ports:
            - "5432:5432"
        volumes_from:
            - database-data
    database-data:
        image: barbasa/postgres-data
    node-app:
        image: barbasa/node-app
        ports:
            - "8881:8881"
        links:
            - database
        environment:
            - DATABASE_URL=postgres://postgres@database:5432/postgres
